version: '3.8'
services:
  swipeshape:
    build: .
    ports:
      - "8080:3000" 
  
    environment:
      DATABASE_URL: ${DATABASE_URL}

    healthcheck:  
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3