version: '3.8'
services:
  swipeshape:
    build: .
    ports:
      - "8080:3000"  # Gardez cette ligne
    # Supprimez networks: (Coolify gère ça)
    environment:
      DATABASE_URL: ${DATABASE_URL}
      # ... (autres variables)
    healthcheck:  # ✅ Gardez ceci
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: swipeshape
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: